name: Format

on:
  push:
  pull_request:
  workflow_call:
    
env:
  CARGO_TERM_COLOR: always

jobs:
  check-format:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - 1.65

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        override: true
    - name: Run tests
      run: cargo fmt --check
