name: Format

on:
  push:
  pull_request:
  workflow_call:
    
env:
  CARGO_TERM_COLOR: always

jobs:
  check-format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo fmt --check
